EPMS.Web/ViewModels/License/LicenseCreateViewModel.cs
using System.Collections.Generic;
using EPMS.Web.Models;

namespace EPMS.Web.ViewModels.License
{
    public class LicenseCreateViewModel
    {
        public LicenseCreateViewModel()
        {
            ModulesList = new List<Module>();
            OldSelectedModules = new List<string>();
            LicenseCoP = new LicenseControlPanel();
        }
        public LicenseControlPanel LicenseCoP { get; set; }
        public IList<Module> ModulesList { get; set; }
        public IList<string> SelectedModules { get; set; }
        public IList<string> OldSelectedModules { get; set; }
    }
}

EPMS.Web/ViewModels/License/LicenseIndexViewModel.cs
using System.Collections.Generic;
using EPMS.Web.Models;

namespace EPMS.Web.ViewModels.License
{
    public class LicenseIndexViewModel
    {
        public IEnumerable<LicenseControlPanel> LicenseControlPanels { get; set; }
    }
}

EPMS.Web/Controllers/LicenseController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using EPMS.Interfaces.IServices;
using EPMS.Web.ModelMappers;
using EPMS.Web.Models;
using EPMS.Web.ViewModels.Common;
using EPMS.Web.ViewModels.License;

namespace EPMS.Web.Controllers
{
    [Authorize]
    public class LicenseController : BaseController
    {
        #region Private
        private readonly ILicenseControlPanelService ControlPanelService;
        private readonly IUserModuleService ModuleService;
        
        #endregion

        #region Constructor
        public LicenseController(ILicenseControlPanelService controlPanelService, IUserModuleService moduleService)
        {
            ControlPanelService = controlPanelService;
            ModuleService = moduleService;
        }

        #endregion

        // GET: LCP/License
        public ActionResult Index()
        {
            LicenseIndexViewModel viewModel = new LicenseIndexViewModel
            {
                LicenseControlPanels = ControlPanelService.GetAll().Select(x => x.CreateFromServerToClient())
            };
            ViewBag.MessageVM = TempData["message"] as MessageViewModel;
            return View(viewModel);
        }
        // GET: LCP/Create
        public ActionResult Create(int? id)
        {
            LicenseCreateViewModel viewModel = new LicenseCreateViewModel();
            viewModel.ModulesList.Add(new Module
            {
                Val = "PMS",
                Text = "Project Management System"
            });
            //viewModel.ModulesList.Add(new Module
            //{
            //    Val = "HRS",
            //    Text = "Human Resource System"
            //});
            viewModel.ModulesList.Add(new Module
            {
                Val = "Mt",
                Text = "Meetings"
            });
            viewModel.ModulesList.Add(new Module
            {
                Val = "CS",
                Text = "Customer Service"
            });
            viewModel.ModulesList.Add(new Module
            {
                Val = "Dashboard",
                Text = "Dashboard"
            });
            //viewModel.ModulesList.Add(new Module
            //{
            //    Val = "NS",
            //    Text = "Notification System"
            //});
            if (id != null)
            {
                viewModel.LicenseCoP = ControlPanelService.FindLicenseById(Convert.ToInt32(id)).CreateFromServerToClient();
                foreach (var modules in viewModel.LicenseCoP.UserModules)
                {
                    viewModel.OldSelectedModules.Add(modules.ModuleName);
                }
            }
            return View(viewModel);
        }
        /// <summary>
        /// POST: LCP/Create
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(LicenseCreateViewModel viewModel)
        {
            if (Request.Form["Deactivate"] != null)
            {
                viewModel.LicenseCoP.Status = false;
                var licenseToUpdate = viewModel.LicenseCoP.CreateFromClientToServer();
                if (ControlPanelService.UpdateLicense(licenseToUpdate, viewModel.SelectedModules, viewModel.OldSelectedModules))
                {
                    TempData["message"] = new MessageViewModel
                    {
                        Message = "License has been Updated",
                        IsUpdated = true
                    };
                    return RedirectToAction("Index");
                }
            }
            if (Request.Form["Activate"] != null)
            {
                // Generate License
                string domain = viewModel.LicenseCoP.Domain;
                long noOfUsers = viewModel.LicenseCoP.NoOfUsers;
                string expiryDate = viewModel.LicenseCoP.EndDate;
                string modules = "";
                foreach (var module in viewModel.SelectedModules)
                {
                    modules = modules + module + ";";
                }
                modules = modules + "HRS;NS;CL;CP;HI";
                var productNo = viewModel.LicenseCoP.ProductNumber;
                var licenseNo = viewModel.LicenseCoP.LicenseNumber;
                var startDate = viewModel.LicenseCoP.StartDate;
                string licenseKey = domain + "|" + viewModel.LicenseCoP.MacAddress + "|" + Convert.ToString(noOfUsers) + "|" +
                                    expiryDate + "|" + modules + "|" + productNo + "|" + licenseNo + "|" + startDate;
                // (string to encrypt, encryption password )
                string encryptedString = EncryptDecrypt.EncryptDecrypt.StringCipher.Encrypt(licenseKey, "123");
                const string emailSubject = "License Key for EPMS";
                string emailBody = "Your License has been generated. License key is = " + encryptedString;
                Utility.SendEmailAsync(viewModel.LicenseCoP.Email, emailSubject, emailBody);
                if (viewModel.LicenseCoP.LicenseControlPanelId == 0)
                {
                    viewModel.LicenseCoP.Status = true;
                    viewModel.LicenseCoP.LicenseKey = encryptedString;
                    var licenseToAdd = viewModel.LicenseCoP.CreateFromClientToServer();
                    if (ControlPanelService.AddLicense(licenseToAdd, viewModel.SelectedModules))
                    {
                        TempData["message"] = new MessageViewModel
                        {
                            Message = "License has been Added",
                            IsSaved = true
                        };
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    viewModel.LicenseCoP.Status = true;
                    viewModel.LicenseCoP.LicenseKey = encryptedString;
                    var licenseToUpdate = viewModel.LicenseCoP.CreateFromClientToServer();
                    if (ControlPanelService.UpdateLicense(licenseToUpdate, viewModel.SelectedModules, viewModel.OldSelectedModules))
                    {
                        TempData["message"] = new MessageViewModel
                        {
                            Message = "License has been Updated",
                            IsUpdated = true
                        };
                        return RedirectToAction("Index");
                    }
                }
            }
            return View(viewModel);
        }
    }
}

EPMS.Web/Views/License/Create.cshtml
@model EPMS.Web.ViewModels.License.LicenseCreateViewModel

@{
    ViewBag.Title = "Create new License";
    Layout = "~/Views/Shared/_LicenseLayout.cshtml";
}

<!-- Navigation Bar -->
<div class="breadcrumb-container" dir="ltr">
    <ul class="xbreadcrumbs">
        <li>
            <a href="~/Dashboard/Index">
                <i class="icon-photon home"></i>
            </a>
        </li>
        <li>
            <a href="~/License/Index">
                Licenses' List
            </a>
        </li>
        <li class="current">
            <a href="javascript:;">@ViewBag.Title</a>
        </li>
    </ul>
</div>
<!-- Page heading -->
<header>
    <i class="icon-big-notepad"></i>
    <h2><small>@ViewBag.Title</small></h2>
</header>
<!--Notifications begin-->
@Html.Partial("_Alert")

@using (Html.BeginForm("Create", "License", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(model => model.LicenseCoP.LicenseControlPanelId)
    if (Model.OldSelectedModules != null)
    {
        for (int i = 0; i < Model.OldSelectedModules.Count(); i++)
        {
            @Html.HiddenFor(model => model.OldSelectedModules[i])
        }
    }
    <div class="container-fluid">
        <div class="control-group row-fluid">
            <div class="span3">
                <label class="control-label" for="CompanyName">Company Name</label>
            </div>
            <div class="span9">
                <div class="controls">
                    @Html.TextBoxFor(model => model.LicenseCoP.CompanyName, new { @id = "CompanyName", @class = "" })
                    @Html.ValidationMessageFor(m => m.LicenseCoP.CompanyName, String.Empty, new { @class = "required" })
                </div>
            </div>
        </div>
        <div class="control-group row-fluid">
            <div class="span3">
                <label class="control-label" for="CompanyWebsite">Website</label>
            </div>
            <div class="span9">
                <div class="controls">
                    @Html.TextBoxFor(model => model.LicenseCoP.Website, new { @id = "CompanyWebsite", @class = "" })
                    @Html.ValidationMessageFor(m => m.LicenseCoP.Website, String.Empty, new { @class = "required" })
                </div>
            </div>
        </div>
        <div class="control-group row-fluid">
            <div class="span3">
                <label class="control-label" for="CompanyEmail">Email</label>
            </div>
            <div class="span9">
                <div class="controls">
                    @Html.TextBoxFor(model => model.LicenseCoP.Email, new { @id = "CompanyEmail", @class = "" })
                    @Html.ValidationMessageFor(m => m.LicenseCoP.Email, String.Empty, new { @class = "required" })
                </div>
            </div>
        </div>
        <div class="control-group row-fluid">
            <div class="span3">
                <label class="control-label" for="CompanyAddress">Address</label>
            </div>
            <div class="span9">
                <div class="controls">
                    @Html.TextBoxFor(model => model.LicenseCoP.Address, new { @id = "CompanyAddress", @class = "" })
                    @Html.ValidationMessageFor(m => m.LicenseCoP.Address, String.Empty, new { @class = "required" })
                </div>
            </div>
        </div>
        <div class="control-group row-fluid">
            <div class="span3">
                <label class="control-label" for="LandLine">LandLine</label>
            </div>
            <div class="span9">
                <div class="controls">
                    @Html.TextBoxFor(model => model.LicenseCoP.LandLine, new { @id = "LandLine", @class = "" })
                    @Html.ValidationMessageFor(m => m.LicenseCoP.LandLine, String.Empty, new { @class = "required" })
                </div>
            </div>
        </div>
        <div class="control-group row-fluid">
            <div class="span3">
                <label class="control-label" for="MobileNumber">Mobile</label>
            </div>
            <div class="span9">
                <div class="controls">
                    @Html.TextBoxFor(model => model.LicenseCoP.Mobile, new { @id = "MobileNumber", @class = "" })
                    @Html.ValidationMessageFor(m => m.LicenseCoP.Mobile, String.Empty, new { @class = "required" })
                </div>
            </div>
        </div>
        <div class="control-group row-fluid">
            <div class="span3">
                <label class="control-label" for="CommercialRegister">Commercial Register</label>
            </div>
            <div class="span9">
                <div class="controls">
                    @Html.TextBoxFor(model => model.LicenseCoP.CommercialRegister, new { @id = "CommercialRegister", @class = "" })
                    @Html.ValidationMessageFor(m => m.LicenseCoP.CommercialRegister, String.Empty, new { @class = "required" })
                </div>
            </div>
        </div>
        <div class="control-group row-fluid">
            <div class="span3">
                <label class="control-label" for="ProductNumber">Product Number</label>
            </div>
            <div class="span9">
                <div class="controls">
                    @Html.TextBoxFor(model => model.LicenseCoP.ProductNumber, new { @id = "ProductNumber", @class = "" })
                    @Html.ValidationMessageFor(m => m.LicenseCoP.ProductNumber, String.Empty, new { @class = "required" })
                </div>
            </div>
        </div>
        <div class="control-group row-fluid">
            <div class="span3">
                <label class="control-label" for="Domain">
                    Domain<a href="javascript:;" class="bootstrap-tooltip" data-placement="top" data-original-title="D:\Projects\EPMS\"><i class="icon-photon info-circle"></i></a>
                </label>
            </div>
            <div class="span9">
                <div class="controls">
                    @Html.TextBoxFor(model => model.LicenseCoP.Domain, new { @id = "Domain", @class = "" })
                    @Html.ValidationMessageFor(m => m.LicenseCoP.Domain, String.Empty, new { @class = "required" })
                </div>
            </div>
        </div>
        @*<div class="control-group row-fluid">
            <div class="span3">
                <label class="control-label" for="LicenseNumber">
                    Mac Address<a href="javascript:;" class="bootstrap-tooltip" data-placement="top" data-original-title="123ABC456DEF"><i class="icon-photon info-circle"></i></a>
                </label>
            </div>
            <div class="span9">
                <div class="controls">
                    @Html.TextBoxFor(model => model.LicenseCoP.MacAddress, new { @id = "Domain", @class = "" })
                    @Html.ValidationMessageFor(m => m.LicenseCoP.MacAddress, String.Empty, new { @class = "required" })
                </div>
            </div>
        </div>*@
        <div id="Dual_Multi_Select_with_Filter_Search" class="control-group row-fluid">
            <div class="span3">
                <label class="control-label" for="dualMulti">
                    Assign Module<a href="javascript:;" class="bootstrap-tooltip" data-placement="top" data-original-title="Human Resource System, Notification System"><i class="icon-photon info-circle"></i></a>
                </label>
            </div>
            <div class="span9">
                <div class="controls">
                    @Html.ListBoxFor(model => model.SelectedModules, new MultiSelectList(Model.ModulesList, "Val", "Text"), new { @class = "", @id = "dualMulti", })
                </div>
            </div>
            <label id="validateCoreModuleError" style="color: #f83535; text-align: center"></label>
        </div>
        <div class="control-group row-fluid">
            <div class="span3">
                <label class="control-label" for="NumberofUsers">Number of Users</label>
            </div>
            <div class="span9">
                <div class="controls">
                    @Html.TextBoxFor(model => model.LicenseCoP.NoOfUsers, new { @id = "NumberofUsers", @class = "" })
                    @Html.ValidationMessageFor(m => m.LicenseCoP.NoOfUsers, String.Empty, new { @class = "required" })
                </div>
            </div>
        </div>
        <div class="control-group row-fluid">
            <div class="span3">
                <label class="control-label" for="LicenseNumber">License Number</label>
            </div>
            <div class="span9">
                <div class="controls">
                    @Html.TextBoxFor(model => model.LicenseCoP.LicenseNumber, new { @id = "LicenseNumber", @class = "" })
                    @Html.ValidationMessageFor(m => m.LicenseCoP.LicenseNumber, String.Empty, new { @class = "required" })
                </div>
            </div>
        </div>
        <div class="control-group row-fluid">
            <div class="span3">
                <label class="control-label" for="LicStartDate">Start Date</label>
            </div>
            <div class="controls span4">
                @Html.TextBoxFor(model => model.LicenseCoP.StartDate, new { @id = "LicStartDate", @class = "col-lg-2 datepickerGregorian form-control cursorHand", onchange = "GregorianToHijri(this, LicStartDateAr)", @readonly = "readonly" })
                @Html.ValidationMessageFor(m => m.LicenseCoP.StartDate, String.Empty, new { @class = "required" })
            </div>
            <div class="controls span4">
                @Html.TextBox("Start Date", null, new { @class = "col-lg-2 datepickerArabic form-control cursorHand", @id = "LicStartDateAr", onchange = "HijriToGregorian(this,'#LicStartDate')", @readonly = "readonly" })
            </div>
        </div>
        <div class="control-group row-fluid">
            <div class="span3">
                <label class="control-label" for="LicEndDate">End Date</label>
            </div>
            <div class="controls span4">
                @Html.TextBoxFor(model => model.LicenseCoP.EndDate, new { @id = "LicEndDate", @class = "col-lg-2 datepickerGregorian form-control cursorHand", onchange = "GregorianToHijri(this, LicEndDateAr)", @readonly = "readonly" })
                @Html.ValidationMessageFor(m => m.LicenseCoP.EndDate, String.Empty, new { @class = "required" })
            </div>
            <div class="controls span4">
                @Html.TextBox("Start Date", null, new { @class = "col-lg-2 datepickerArabic form-control cursorHand", @id = "LicEndDateAr", onchange = "HijriToGregorian(this,'#LicEndDate')", @readonly = "readonly" })
            </div>
        </div>
        <div class="control-group row-fluid">
            <div class="span3 span-inset">
                <button type="submit" class="btn" name="Activate" @*onclick="validateCoreModules(event)"*@>Activate</button>
            </div>
        </div>
        @if (Model.LicenseCoP.LicenseControlPanelId > 0)
        {
            <div class="control-group row-fluid">
                <div class="span3 span-inset">
                    <button type="submit" class="btn" name="Deactivate">Deactivate</button>
                </div>
            </div>
        }
    </div>
}
<script>
    $(document).ready(function () {
        $("#dualMulti option").each(function (key, value) {
            var listText = $(this).val();
            var element = $(this);
            if (listText == "HRS" || listText == "NS") {
                $(element).attr("selected", "selected");
                $(element).hide();
            }
        });
        //$("ul.pickList_targetListContainer li").each(function () {
        //    $('li:contains("HRS")').hide();
        //    $('li:contains("NS")').hide();
        //});
        if ('@Model.LicenseCoP.UserModules.Count' > 0) {

            var modulesList = '@Html.Raw(Json.Encode(Model.LicenseCoP.UserModules))';
            var parsed = JSON.parse(modulesList);
            $("#dualMulti option").each(function (key, value) {
                var listText = $(this).val();
                var element = $(this);
                $.each(parsed, function (key, value) {
                    if (value.ModuleName == listText) {
                        $(element).attr("selected", "selected");
                    }
                });
            });
        }
        $("#dualMulti").pickList({
            sourceListLabel: "Modules",
            targetListLabel: "Client Modules",
        });
        if ('@Model.LicenseCoP.LicenseControlPanelId' > 0) {
            $("#LicStartDateAr").val(ConvertDates($("#LicStartDate").val(), "gregorian", "islamic"));
            $("#LicEndDateAr").val(ConvertDates($("#LicEndDate").val(), "gregorian", "islamic"));
        }
        if ($("#NumberofUsers").val() == 0) {
            $("#NumberofUsers").val("");
        }
    });
    function validateCoreModules(event) {
        var selectedModules = $("#dualMulti").val();
        var containsCoreModules = 2;
        //hr, contact, notification sys, company profile , help
        for (var i = 0; i < selectedModules.length; i++) {
            if (selectedModules[i] == "HRS") {
                containsCoreModules--;
            }
            else if (selectedModules[i] == "NS") {
                containsCoreModules--;
            }
        }
        if (containsCoreModules > 0) {
            $("#validateCoreModuleError").text("Please Select Core Modules");
            $("#dualMulti").focus();
            event.preventDefault();
            return false;
        }
        $("#validateCoreModuleError").text("");
        return true;
    }
</script>

EPMS.Web/Views/License/Index.cshtml
@model EPMS.Web.ViewModels.License.LicenseIndexViewModel

@{
    ViewBag.Title = "Licenses' List";
    Layout = "~/Views/Shared/_LicenseLayout.cshtml";
    //Layout = null;
    var direction = EPMS.Web.Resources.Shared.Common.TextDirection;
}

<!-- Navigation Bar -->
<div class="breadcrumb-container" dir="ltr">
    <ul class="xbreadcrumbs">
        <li>
            <a href="~/License/Index">
                <i class="icon-photon home"></i>
            </a>
        </li>
        <li class="current">
            <a href="javascript:;">@ViewBag.Title</a>
        </li>
    </ul>
</div>
<!-- Page heading -->
<header>
    <i class="icon-big-notepad"></i>
    <h2><small>@ViewBag.Title</small></h2>
    <h3> <small><a href="~/License/Create">Create new License</a></small></h3>
</header>
<!--Notifications begin-->
@Html.Partial("_Alert")

<form class="form-horizontal">
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <table id="LicensesTable" class="table table-striped table-responsive">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Client Name</th>
                            <th>License No.</th>
                            <th>Expiry Date</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.LicenseControlPanels.ToList())
                        {
                            <tr>
                                <td>@item.LicenseControlPanelId</td>
                                <td>
                                    @if (direction == "ltr")
                                    {
                                        @Html.ActionLink(@item.CompanyName, "Create", new {id = item.LicenseControlPanelId})
                                    }
                                    else
                                    {
                                        @Html.ActionLink(@item.CompanyName, "Create", new { id = item.LicenseControlPanelId })
                                    }
                                </td>
                                <td>
                                    @item.LicenseNumber
                                </td>
                                <td>
                                    @item.EndDate
                                </td>
                                <td>
                                    @if (@item.Status)
                                    {
                                        @EPMS.Web.Resources.Help.Help.Activated
                                        }
                                    else
                                    {
                                        @EPMS.Web.Resources.Help.Help.Deactivated
                                            }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function () {
        $('#LicensesTable').dataTable({
            "sPaginationType": "bootstrap",
            "aoColumns": [
                { "bVisible": false },
                  null,
                  null,
                  null,
                  null
            ],
            "fnInitComplete": function () {
                $(".dataTables_wrapper select").select2({
                    dropdownCssClass: 'noSearch'
                });
            }
        });
    });
</script>